config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Create CRUD routes after using "scaffold" command
  resources :tasks
  
  # get 'home/index'
  get 'home/about'
  # root 'home#index'
  root 'tasks#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
    @my_name = 'Artur'
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index show ]
  before_action :correct_user, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    # @task = Task.new
    @task = current_user.tasks.build
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    # @task = Task.new(task_params)
    @task = current_user.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_url(@task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully deleted." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    redirect_to tasks_path, notice: "Not authorized to edit this task" if @task.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :description, :deadline, :is_completed, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/markdown_helper.rb
module MarkdownHelper
  def markdown(text)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
    markdown.render(text).html_safe
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-primary bg-primary" data-bs-theme="dark">
  <div class="container-fluid">
  	<%= link_to "To-Do List", root_path, class:"navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "About", home_about_path, class:"nav-link" %>
        </li>
      </ul>

      <ul class="navbar-nav justify-content-end">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us</h1>

<p>Hello, my name is <%= @my_name %>.</p>

app/views/home/index.html.erb
<h1>Hello World</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>To-Do List</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'home/header' %>

    <div class="container">
      <br>
      <% if notice %>
        <%= render "layouts/alerts" %>
      <% end %>

      <%= yield %>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.label :title, style: "display: block", class:"form-label" %>
    <%= form.text_field :title, class:"form-control", placeholder:"Enter your task" %>
  </div>

  <div class="field mb-3">
    <%= form.label :description, style: "display: block", class:"form-label" %>
    <%= form.text_area :description, style:"box-sizing: border-box", class:"form-control", placeholder:"You can use Markdown to describe your task" %>
  </div>

  <div class="field mb-3">
    <%= form.label :deadline, style: "display: block", class:"form-label" %>
    <%= form.datetime_field :deadline, class:"form-control" %>
  </div>

  <div class="field mb-3 form-check">
    <%= form.check_box :is_completed, class:"form-check-input" %>
    <%= form.label :is_completed, style:"display: block", class:"form-check-label" %>
  </div>

  <div class="field mb-3">
    <%= form.number_field :user_id, id: :task_user_id, class:"form-control", value:current_user.id, type: :hidden %>
  </div>

  <div class="actions mb-3">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <p>
    <strong>Title:</strong>
    <%= task.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= task.description %>
  </p>

  <p>
    <strong>Deadline:</strong>
    <%= task.deadline %>
  </p>

  <p>
    <strong>Completed:</strong>
    <%= task.is_completed %>
  </p>

</div>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render "form", task: @task %>

<%= button_to "Delete", @task, method: :delete, class:"btn btn-danger" %>

app/views/tasks/index.html.erb
<% if user_signed_in? %>
  <div id="tasks">
    <div class="row row-cols-1 row-cols-md-3 g-4">
      <% @tasks.each do |task| %>
        <% if task.user == current_user %>
          <div class="col">
            <% card_class = if task.is_completed
              "border-success"
            elsif not task.deadline
              "border-secondary"
            elsif DateTime.now >= task.deadline
              "border-danger"
            elsif (task.deadline - Time.now) < 1.day
              "border-warning"
            else
              "border-secondary"
            end %>
            
            <div class="card h-100 <%= card_class %>" style="border-width:2px;">
              <a href="<%= task_path(task) %>" style="text-decoration: none; color: inherit;">
                <div class="card-body">
                  <h2 class="card-title"><%= task.title %></h2>
                  <h6 class="card-subtitle mb-2 text-body-secondary"><%= task.deadline %></h6>
                  <p class="card-text"><%= markdown(task.description) %></p>
                </div>
              </a>
            </div>
          </div>
        <% end %>
      <% end %>

      <div class="col">
        <div class="card h-100 text-center border-primary" style="border-width:2px;">
          <div class="card-body">
            <h5 class="card-title">New Task</h5>
            <% if @tasks.length() == 0 %>
              <p class="card-text">You have not added any tasks yet</p>
            <% else %>
              <p class="card-text">Add a new task to your list</p>
            <% end %>
            <%= link_to "Add", new_task_path, class:"btn btn-primary" %>
          </div>
        </div>
      </div>

    </div>
  </div>
<% else %>
  <p>You must be logged in to create a task.</p>
<% end %>

app/views/tasks/new.html.erb
<h1>Add task</h1>

<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<div class="card">
  <div class="card-body">
    <h1 class="card-title"><%= @task.title %></h1>
    <h4 class="card-subtitle mb-2 text-body-secondary"><%= @task.deadline %></h4>
    <p class="card-text"><%= markdown(@task.description) %></p>
    <%= link_to "Edit", edit_task_path(@task), class:"btn btn-primary" %>
  </div>
</div>